In [1]:
import numpy as np

In [2]:
an_array = np.array([3, 33, 333]) #Create a rank 1 array

In [3]:
print type(an_array)

<type 'numpy.ndarray'>


In [4]:
print an_array.shape

(3L,)


In [5]:
print an_array[0],an_array[1],an_array[2]

3 33 333


In [6]:
an_array[0] = 8888

In [7]:
print an_array

[8888   33  333]


In [8]:
another = np.array([[11,12,13],[21,22,23]])

In [9]:
print another

[[11 12 13]
 [21 22 23]]


In [10]:
print "the shape is 2 rows, 3 columns: ", another.shape

the shape is 2 rows, 3 columns:  (2L, 3L)


In [11]:
print "Accessing elements [0,0], [0,1] and [1,0] of the ndarray: ",another[0,0],another[0,1],another[1,0]

Accessing elements [0,0], [0,1] and [1,0] of the ndarray:  11 12 21


In [12]:
ex1 = np.zeros((2,2))

In [13]:
ex1

array([[ 0.,  0.],
       [ 0.,  0.]])

In [14]:
ex2 = np.full((2,2),9.0)

In [15]:
ex2

array([[ 9.,  9.],
       [ 9.,  9.]])

In [16]:
ex3 = np.eye(2,2)

In [17]:
ex3

array([[ 1.,  0.],
       [ 0.,  1.]])

In [18]:
ex4 = np.ones((1,2))

In [19]:
ex4

array([[ 1.,  1.]])

In [20]:
print ex4.shape

(1L, 2L)


In [21]:
ex5 = np.random.random((2,2))

In [22]:
print ex5

[[ 0.54375013  0.13369283]
 [ 0.33904345  0.23045863]]


# Array Indexing

In [23]:
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])

In [24]:
print an_array

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [25]:
a_slice = an_array[:2,1:3]

In [26]:
print a_slice

[[12 13]
 [22 23]]


In [27]:
a_slice[0,0]=999

In [28]:
print an_array

[[ 11 999  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]]


In [29]:
copy_slice = np.array(an_array[:2,1:3])

In [30]:
copy_slice

array([[999,  13],
       [ 22,  23]])

In [31]:
copy_slice[0,1] = 987

In [32]:
print copy_slice

[[999 987]
 [ 22  23]]


In [33]:
an_array

array([[ 11, 999,  13,  14],
       [ 21,  22,  23,  24],
       [ 31,  32,  33,  34]])

In [34]:
row_rank2 = an_array[1:2,:]

In [35]:
print row_rank2,row_rank2.shape

[[21 22 23 24]] (1L, 4L)


In [36]:
row_rank1 = an_array[0,:]

In [37]:
print row_rank1,row_rank1.shape

[ 11 999  13  14] (4L,)


In [38]:
col_rank1 = an_array[:,1]

In [39]:
col_rank1

array([999,  22,  32])

In [40]:
col_rank2 = an_array[:,1:2]

In [41]:
print col_rank2,col_rank2.shape

[[999]
 [ 22]
 [ 32]] (3L, 1L)


In [42]:
an_array = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])

In [43]:
print 'Original Array'
print an_array

Original Array
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [44]:
col_indices = np.array([0,1,2,0])
print '\nCol indices picked : ',col_indices

row_indices = np.arange(4)
print '\nRows indices picked : ', row_indices


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [45]:
for row,col in zip(row_indices,col_indices):
    print row,", ",col

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [46]:
print 'Values in the array at those indices: ',an_array[row_indices,col_indices]

Values in the array at those indices:  [11 22 33 41]


In [47]:
an_array[row_indices,col_indices]+=10000

In [48]:
print '\nChanged Array:'
print an_array


Changed Array:
[[10011    12    13]
 [   21 10022    23]
 [   31    32 10033]
 [10041    42    43]]


# Boolean Indexing

In [49]:
an_array = np.array([[11,12],[21,22],[31,32]])

In [50]:
print an_array

[[11 12]
 [21 22]
 [31 32]]


In [51]:
an_array > 35

array([[False, False],
       [False, False],
       [False, False]], dtype=bool)

In [54]:
an_array[(an_array>15) & (an_array<30)]

array([21, 22])

In [55]:
an_array[an_array %2==0]

array([12, 22, 32])

In [56]:
an_array[an_array%2==0]+=100

In [57]:
print an_array

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [58]:
ex1 = np.array([11,12])
print ex1.dtype

int32


In [62]:
ex2 = np.array([11.0,12.0])

In [63]:
print ex2.dtype

float64


In [64]:
ex3 = np.array([11,21],dtype=np.int64)

In [66]:
print ex3

[11 21]


In [67]:
ex4 = np.array([11.1,12.7],dtype=np.int64)

In [68]:
print ex4

[11 12]


In [72]:
ex5 = np.array([11,21],dtype=np.float32)

In [73]:
print ex5

[ 11.  21.]


# Arthmetic Array Operations

In [88]:
x = np.array([[111,112],[121,122]],dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]],dtype=np.float64)
print x
print 
print y

[[111 112]
 [121 122]]

[[ 211.1  212.1]
 [ 221.1  222.1]]


In [79]:
print x+y
print 
print np.add(x,y)

[[ 322.1  324.1]
 [ 342.1  344.1]]

[[ 322.1  324.1]
 [ 342.1  344.1]]


In [80]:
print x-y
print 
print np.subtract(x,y)

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [89]:
print x*y
print
print np.multiply(x,y)

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]


In [96]:
print x/y
print
print np.divide(x,y)

[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]

[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]


In [97]:
print np.exp(x)

[[  1.60948707e+48   4.37503945e+48]
 [  3.54513118e+52   9.63666567e+52]]


In [98]:
print np.sqrt(x)

[[ 10.53565375  10.58300524]
 [ 11.          11.04536102]]


# Basic Statistical Operations

In [108]:
arr = 10*np.random.randn(2,5)

In [109]:
print arr

[[ -9.31032783 -17.52200622  -9.640827     3.54208171  -5.23759047]
 [  1.55726568  -0.44661871  -8.93989404  -3.17766163   1.58615557]]


In [110]:
print arr.mean()

-4.75894229291


In [111]:
#compute the means by row
print arr.mean(axis=1)

[-7.63373396 -1.88415063]


In [112]:
#mean by columns
print arr.mean(axis=0)

[-3.87653107 -8.98431246 -9.29036052  0.18221004 -1.82571745]


In [117]:
print arr.sum()

-47.5894229291


In [115]:
print np.median(arr,axis=0)

[-3.87653107 -8.98431246 -9.29036052  0.18221004 -1.82571745]


In [116]:
print np.median(arr,axis=1)

[-9.31032783 -0.44661871]


In [118]:
print arr.sum(axis=0)

[ -7.75306214 -17.96862493 -18.58072104   0.36442009  -3.65143491]


In [119]:
print arr.sum(axis=1)

[-38.1686698   -9.42075313]


# Sorting

In [121]:
unsorted = np.random.randn(10)
print unsorted

[ 0.4413814   0.00400489  0.26341457  0.91488406  1.91471344  0.28832049
  0.73456555 -0.34575116  1.31893918 -0.12237782]


In [123]:
sorted = np.array(unsorted)
sorted.sort()

print sorted
print
print unsorted

[-0.34575116 -0.12237782  0.00400489  0.26341457  0.28832049  0.4413814
  0.73456555  0.91488406  1.31893918  1.91471344]

[ 0.4413814   0.00400489  0.26341457  0.91488406  1.91471344  0.28832049
  0.73456555 -0.34575116  1.31893918 -0.12237782]


In [124]:
unsorted.sort()

In [125]:
print unsorted

[-0.34575116 -0.12237782  0.00400489  0.26341457  0.28832049  0.4413814
  0.73456555  0.91488406  1.31893918  1.91471344]


# Finding Unique elements


In [127]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print s1,s2

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [128]:
print np.intersect1d(s1,s2)

['bulb' 'chair']


In [130]:
print np.union1d(s1,s2)

['bulb' 'chair' 'desk' 'lamp']


In [131]:
print np.setdiff1d(s1,s2)

['desk']


In [133]:
print np.in1d(s1,s2) #element in s1 that are in s2

[False  True  True]


In [135]:
print s1[np.in1d(s1,s2)]

['chair' 'bulb']


# Broadcasting

In [137]:
start = np.zeros((4,3))
print start

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [140]:
add_rows = np.array([[0,1,2]])

In [141]:
y = start+add_rows
print y

[[ 0.  1.  2.]
 [ 0.  1.  2.]
 [ 0.  1.  2.]
 [ 0.  1.  2.]]


In [144]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print add_cols

[[0]
 [1]
 [2]
 [3]]


In [145]:
y = start+add_cols
print y

[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]


In [146]:
add_scalar = np.array([1])
print start+add_scalar

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [150]:
a = np.array([[0,0],[0,0]])
b1 = np.array([[1,1]])
b2 = 1
print a+b1
print a+b2

[[1 1]
 [1 1]]
[[1 1]
 [1 1]]


# Speed Test: ndarray vs. list

In [153]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits = 1000

In [155]:
nd_array = arange(size)
print type(nd_array)

<type 'numpy.ndarray'>


In [160]:
timer_numpy = Timer("nd_array.sum()","from __main__ import nd_array")

print "Time taken by numpy ndarray: %f seconds" %(timer_numpy.timeit(timeits)/timeits)

Time taken by numpy ndarray: 0.000918 seconds


In [161]:
a_list = list(range(size))
print type(a_list)

<type 'list'>


In [164]:
#timer_list = Timer("sum(a_list)","from __main__ import a_list")#
#print "Time taken by list: %f seconds" %(timer_list.timeit(timeits)/timeits)

Time taken by list: 0.089650 seconds


# Read or Write to Disk:

## Binary format:

In [165]:
x = np.array([23.23, 24.24])

In [166]:
np.save('an_array', x)

In [167]:
np.load('an_array.npy')

array([ 23.23,  24.24])

## Text Format:

In [168]:
np.savetxt('array.txt', X=x, delimiter=',')

In [169]:
!cat array.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [170]:
np.loadtxt('array.txt',delimiter=",")

array([ 23.23,  24.24])

## Dot Product on Matrices and Inner Product on Vectors:

In [171]:
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print x2d
print
print y2d

[[1 1]
 [1 1]]

[[2 2]
 [2 2]]


In [172]:
print np.dot(x2d,y2d)

[[4 4]
 [4 4]]


In [173]:
a1d = np.array([9, 9])
b1d = np.array([10, 10])

print a1d.dot(b1d)
print
print b1d.dot(a1d)

180

180


In [175]:
print x2d.dot(a1d)
print
print np.dot(a1d, b1d)

[18 18]

180


In [179]:
x = np.random.rand(8)
y = np.random.rand(8)
print x
print y

[ 0.43680909  0.63768256  0.61919296  0.35054564  0.12981754  0.74092613
  0.77707203  0.76290753]
[ 0.59881604  0.77780075  0.06182162  0.346134    0.39921365  0.60501078
  0.06080316  0.59053602]


In [180]:
np.maximum(x,y)

array([ 0.59881604,  0.77780075,  0.61919296,  0.35054564,  0.39921365,
        0.74092613,  0.77707203,  0.76290753])

In [184]:
arr = np.arange(20)
print arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [185]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [186]:
x_1 = np.array([1,2,3,4,5])
y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [187]:
out = np.where(filter, x_1,y_1)
print out

[ 1 22  3 44  5]


In [189]:
mat = np.random.rand(5,5)


In [190]:
np.where(mat>0.5,1000,-1)

array([[  -1,   -1, 1000,   -1, 1000],
       [  -1, 1000, 1000,   -1,   -1],
       [1000, 1000, 1000, 1000, 1000],
       [1000,   -1,   -1,   -1, 1000],
       [  -1, 1000, 1000,   -1, 1000]])

In [191]:
arr_bools = np.array([True, False, True, True, False])

In [192]:
arr_bools.any()

True

In [193]:
arr_bools.all()

False

In [196]:
Y = np.random.normal(size=(1,5))[0]
print Y

[-0.33195816  0.37554218  0.38347221  0.06164637 -1.42308838]


In [197]:
Z = np.random.randint(low=2,high=50,size=4)
print Z

[23 22 23 43]


In [204]:
np.random.permutation(Z)

array([22, 23, 23, 43])

In [206]:
np.random.uniform(size=4)

array([ 0.00248028,  0.37292632,  0.68090356,  0.86465106])

In [207]:
np.random.normal(size=4)

array([ 0.61933686, -0.05536328, -1.67461985,  1.1172294 ])

# Merging data sets:

In [208]:
K = np.random.randint(low=2,high=50,size=(2,2))
print K

print
M = np.random.randint(low=2,high=50,size=(2,2))
print M

[[23 44]
 [ 9 24]]

[[ 9 23]
 [ 9 36]]


In [209]:
np.vstack((K,M))

array([[23, 44],
       [ 9, 24],
       [ 9, 23],
       [ 9, 36]])

In [210]:
np.hstack((K,M))

array([[23, 44,  9, 23],
       [ 9, 24,  9, 36]])

In [211]:
np.concatenate([K, M], axis = 0)

array([[23, 44],
       [ 9, 24],
       [ 9, 23],
       [ 9, 36]])

In [212]:
np.concatenate([K, M.T], axis=1)

array([[23, 44,  9,  9],
       [ 9, 24, 23, 36]])