In [2]:
import numpy as np

In [3]:
an_array = np.array([3, 33, 333]) #Create a rank 1 array

In [4]:
print type(an_array)

<type 'numpy.ndarray'>


In [7]:
print an_array.shape

(3L,)


In [8]:
print an_array[0],an_array[1],an_array[2]

3 33 333


In [9]:
an_array[0] = 8888

In [10]:
print an_array

[8888   33  333]


In [11]:
another = np.array([[11,12,13],[21,22,23]])

In [12]:
print another

[[11 12 13]
 [21 22 23]]


In [13]:
print "the shape is 2 rows, 3 columns: ", another.shape

the shape is 2 rows, 3 columns:  (2L, 3L)


In [14]:
print "Accessing elements [0,0], [0,1] and [1,0] of the ndarray: ",another[0,0],another[0,1],another[1,0]

Accessing elements [0,0], [0,1] and [1,0] of the ndarray:  11 12 21


In [15]:
ex1 = np.zeros((2,2))

In [16]:
ex1

array([[ 0.,  0.],
       [ 0.,  0.]])

In [18]:
ex2 = np.full((2,2),9.0)

In [19]:
ex2

array([[ 9.,  9.],
       [ 9.,  9.]])

In [24]:
ex3 = np.eye(2,2)

In [25]:
ex3

array([[ 1.,  0.],
       [ 0.,  1.]])

In [26]:
ex4 = np.ones((1,2))

In [27]:
ex4

array([[ 1.,  1.]])

In [28]:
print ex4.shape

(1L, 2L)
